캐시비 추가
yourtablecloth/TableClothCatalog pull request #62
Opened 2024-03-05 05:03 UTC by skyfly07

캐시비도 티머니처럼 로그인시 TouchEn이 필요해서 추가했습니다.

2024-03-05 05:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yourtablecloth/TableClothCatalog?pullRequest=62) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yourtablecloth/TableClothCatalog?pullRequest=62) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yourtablecloth/TableClothCatalog?pullRequest=62) it.</sub>

2024-03-09 16:02 UTC, rkttu requested changes
이미지 파일 이름을 한글 대신 영어 (Cashbee.png)로 변경해주시면 감사하겠습니다.

2024-03-09 21:03 UTC, skyfly07 commented
> 이미지 파일 이름을 한글 대신 영어 (Cashbee.png)로 변경해주시면 감사하겠습니다.

파일명 수정 완료했습니다.

2024-03-10 06:55 UTC, rkttu reviewed
Id 부분의 값과 파일 이름을 맞춰서 기재 부탁드립니다. 이 부분이 일치하지 않으면, 식탁보 애플리케이션에서는 기본 로고로 Fallback 처리하여 대체 아이콘을 보여주게 됩니다.

우선 이번 PR은 approve 하겠습니다.

2024-03-10 06:55 UTC, merged

2024-03-10 06:57 UTC, rkttu commented
아울러, 아이디가 겹친 부분이 확인되어, TMoney 대신 Cashbee로 아이디 값을 다시 조정했습니다. 이렇게 기재하는 것이 원래 PR 제출 의도와 다른 경우, 새로운 PR 제출을 부탁드립니다.